default_stages: [commit]

repos:
  - repo: https://github.com/python-poetry/poetry
    rev: "1.8.2"
    hooks:
      - id: poetry-check
      - id: poetry-lock
        name: poetry-lock-check
        args: ["--check"]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "v4.5.0"
    hooks:
      - id: check-added-large-files
      - id: check-ast
      - id: check-builtin-literals
      - id: check-byte-order-marker
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-json
      - id: check-merge-conflict
      - id: check-toml
      - id: check-yaml
      - id: debug-statements
      - id: end-of-file-fixer
      - id: fix-encoding-pragma
        args: [--remove]
      - id: mixed-line-ending
        args: [--fix=lf]
      - id: trailing-whitespace

  - repo: https://github.com/psf/black
    rev: "24.3.0"
    hooks:
      - id: black

  - repo: https://github.com/asottile/pyupgrade
    rev: "v3.15.2"
    hooks:
      - id: pyupgrade
        args: [--py37-plus]

  - repo: https://github.com/PyCQA/autoflake
    rev: "v2.3.1"
    hooks:
      - id: autoflake
        args:
          - --in-place
          - --remove-unused-variables
          - --remove-all-unused-imports
          - --expand-star-imports

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: "v0.4.4"
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format
