name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    name: Publish Release
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 0

      - name: Generate Changelog
        id: changelog
        uses: mikepenz/release-changelog-builder-action@v5
        with:
          mode: "COMMIT"

      - name: Update Changelog
        uses: stefanzweifel/changelog-updater-action@v1.12.0
        with:
          latest-version: ${{ github.ref_name }}
          release-notes: ${{ steps.changelog.outputs.changelog }}

      - name: Commit Changes
        uses: stefanzweifel/git-auto-commit-action@v5.2.0
        with:
          branch: main
          commit_message: "chore(main): release ${{ github.ref_name }}"
          file_pattern: CHANGELOG.md
